spring:
  application:
    name: user-management
  cloud:
    config:
      enabled: true
    discovery:
      enabled: false
    jpa:
      properties:
        hibernate:
          jdbc:
            batch_size: 20
  config:
    import: optional:configserver:http://localhost:8888

server:
  servlet:
    context-path: /api/store/user-management
  port: 8080

spring.datasource:
  url: jdbc:postgresql://localhost:5434/postgres
  username: postgres
  password: admin
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 10

forex-service:
  ribbon:
    listOfServers: localhost:8000

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method